---
kind: pipeline
type: docker
name: debian-unstable

steps:
- name: debian-build
  image: dankamongmen/unstable_builder:2020-08-15a
  commands:
    - export LANG=en_US.UTF-8
    - apt-get -y install nettle-dev
    - mkdir build
    - cd build
    - cmake -DUSE_LIBZFS=off ..
    - make
---
kind: pipeline
type: docker
name: ubuntu-focal

steps:
- name: ubuntu-build
  image: dankamongmen/focal:2020-08-14a
  commands:
    - export LANG=en_US.UTF-8
    - apt-get -y install nettle-dev
    - mkdir build
    - cd build
    - cmake -DUSE_LIBZFS=off ..
    - make
