---
kind: pipeline
type: docker
name: debian-unstable

steps:
- name: debian-build
  image: dankamongmen/unstable_builder:2020-10-10a
  commands:
    - export LANG=en_US.UTF-8
    - apt-get -y update
    - apt-get -y install nettle-dev
    - apt-get -y upgrade
    - mkdir build
    - cd build
    - cmake -DUSE_LIBZFS=off ..
    - make
