---
kind: pipeline
type: docker
name: debian-unstable

steps:
- name: debian-build
  image: dankamongmen/unstable_builder:2020-04-18e
  commands:
    - export LANG=en_US.UTF-8
    - autoreconf -fis
    - ./configure
    - make
    - make test
---
kind: pipeline
type: docker
name: ubuntu-focal

steps:
- name: ubuntu-build
  image: dankamongmen/focal:2020-04-18c
  commands:
    - export LANG=en_US.UTF-8
    - DEBIAN_FRONTEND=noninteractive apt-get --yes install autoconf-archive xsltproc
    - autoreconf -fis
    - ./configure
    - make
    - make test
